steps:
- name: 'gcr.io/cloud-builders/yarn'
  args: ['install']
- name: 'gcr.io/cloud-builders/yarn'
  args: ['build']
- name: 'gcr.io/cloud-builders/gsutil'
  args: [
    '-h',
    'Cache-Control:no-cache',
    'cp',
    '-z',
    'html,js',
    '-a',
    'public-read',
    'index.html',
    'app.js',
    'gs://${_UPLOAD_BUCKET}/create-sjis-csv'
  ]
